CREATE TABLE [dbo].[Users]
(
	[Id] NVARCHAR(256) PRIMARY KEY,
	[UserName] NVARCHAR(150) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(256) NOT NULL,
	[Points] INT NOT NULL,
	[UntilPoints] DATETIME NOT NULL
)
